### ISSUE TITLE
Several points related to the README

### ISSUE THREAD

**Issue by lucamug** [miniBill/elm-ui-with-context#1]
## The README examples of type aliases are missing the keyword "alias".

"How to use it", point #3, mentions "type aliases" but the example are missing "alias".

Moreover it It could be better to have the type aliases example on multiple lines as they are easier to copy and paste.

Also there is an extra type alias that I needed in my code, so the total type aliases definition in my code base are:

```elm
type alias Element msg =
    Element.WithContext.Element Context msg

type alias Attribute msg =
    Element.WithContext.Attribute Context msg

type alias Attr decorative msg =
    Element.WithContext.Attr Context decorative msg
```

Having the code on multiple line could be good also for the imports:

```elm
import Element.WithContext exposing (..)
import Element.WithContext.Background as Background
import Element.WithContext.Border as Border
import Element.WithContext.Font as Font
import Element.WithContext.Input as Input
```

## Specific functions

Could be good to have `element` moved/grouped together the specific function that this module add to elm-ui (see `element`).

By the way, cool library!

**Comment by miniBill** [comment]
Thank you for all the issues!
