### ISSUE TITLE
Possible "shortcuts" 

### ISSUE THREAD

**Issue by lucamug** [miniBill/elm-ui-with-context#4]
In my app I tend to skip the `(context -> property)` step so I created these "shortcuts":

```elm
elementWithContext : (Context -> Element msg) -> Element msg
elementWithContext =
    with identity

attrWithContext : (Context -> Attribute msg) -> Attribute msg
attrWithContext =
    withAttribute identity
```

While everybody can create these on their own I was wondering if it would we worth to have them in the library too, especially for beginners, or at least mentioned in the docs somewhere.

Note: probably a third shortcut is missing (see https://github.com/miniBill/elm-ui-with-context/issues/3)

**Comment by miniBill** [comment]
Can you show me how you use these in a wider context?

**Comment by lucamug** [comment]
EDIT: I rewrote the example and created an Ellie. `view1` and `view2` are two examples of how the two "shortcuts" above would work.

For example (Ellie: https://ellie-app.com/cBBQFDQGRYca1):

```elm
module Main exposing (main)

import Element.WithContext exposing (..)
import Element.WithContext.Background as Background
import Element.WithContext.Font as Font
import Html


type alias Palette =
    { background : Color
    , onBackground : Color
    }


type alias Context =
    { palette : Palette }


palette =
    { light = { background = rgb 1 1 1, onBackground = rgb 0 0 0 }
    , dark = { background = rgb 0 0 0, onBackground = rgb 1 1 1 }
    }


main : Html.Html msg
main =
    Html.div []
        [ layout { palette = palette.light } [] <| row [] [ view1, view2 ]
        , layout { palette = palette.dark } [] <| row [] [ view1, view2 ]
        ]


type alias Element msg =
    Element.WithContext.Element Context msg


type alias Attribute msg =
    Element.WithContext.Attribute Context msg


elementWithContext : (Context -> Element msg) -> Element msg
elementWithContext =
    with identity


attrWithContext : (Context -> Attribute msg) -> Attribute msg
attrWithContext =
    withAttribute identity


view1 =
    el
        [ attrWithContext <| \c -> Background.color c.palette.background
        , attrWithContext <| \c -> Font.color c.palette.onBackground
        ]
        (text "view1")


view2 =
    elementWithContext <|
        \c ->
            el
                [ Background.color c.palette.background
                , Font.color c.palette.onBackground
                ]
                (text "view2")
```

I chose the right palette (dark or light) when I call `layout` so that I don't need to do that again later.

Does it make sense?

**Comment by miniBill** [comment]
Yeah it does... I think I'll call them `withContext` and `withContextAttribute`... Probably going to drop in 1.1.0

**Comment by miniBill** [comment]
(just a small note, `withContextAttribute <| \c -> Font.color c.palette.onBackground` is equivalent to `withAttribute .palette <| \palette -> Font.color palette.onBackground`)
